import './app.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/about">About</Link> |
          <Link href="/profile">Profile</Link> |
          <Link href="/dashboard">Dashboard</Link>|
          <Link href="/todos">Todos</Link> |
          <Link href="/game">Game</Link>

        </nav>
        {children}

        <footer>

        </footer>
      </body>
    </html>
  )
}
