//import './app.css'
import Link from 'next/link'

export const metadata = {
    title: 'Marketing',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <h1>Marketing</h1>
                {children}

            </body>
        </html>
    )
}
